[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg://lmc:lmc@localhost:5432/lmc

[loggers]
keys = root
handlers =
level = WARN

[handlers]

[formatters]

[logger_root]
level = WARN
handlers =
